# Generated by Django 6.0 on 2026-02-14 00:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bought', models.BooleanField(default=False)),
                ('shoe_type', models.CharField(max_length=50)),
                ('shoe_color', models.CharField(max_length=50)),
                ('shoe_material', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shoe_todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('I', 'immediately'), ('T', 'Today'), ('W', 'Within a week'), ('N', 'No rush')], default='T', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bought', models.BooleanField(default=False)),
                ('shoe_type', models.CharField(blank=True, max_length=50)),
                ('shoe_color', models.CharField(blank=True, max_length=50)),
                ('shoe_material', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_amount', models.IntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='firstapp.cart')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('shoe_color', models.CharField(choices=[('B', 'Brown'), ('BL', 'Black'), ('N', 'Navy'), ('W', 'White'), ('R', 'Red')], max_length=2)),
                ('shoe_material', models.CharField(choices=[('FL', 'Faux Leather'), ('F', 'Fabric'), ('L', 'Leather')], max_length=2)),
                ('shoe_type', models.CharField(choices=[('B', 'Boots'), ('W', 'Wedges'), ('BF', 'Ballet Flats'), ('S', 'Sandals'), ('C', 'Clogs'), ('ST', 'Stilettos'), ('SN', 'Sneakers')], max_length=2)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('role', models.CharField(choices=[('C', 'Cashier'), ('M', 'Manager'), ('S', 'Supervisor'), ('SL', 'Shift Lead')], default='C', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
