# Generated by Django 6.0 on 2026-02-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='customer_order',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
